In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data3=pd.read_csv("data.csv")
data3

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
x=data3["YearsExperience"]
x

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

In [4]:
y=data3["Salary"]
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.33,random_state=42)

In [12]:
x_train_reshaped =x_train.values.reshape(-1,1)
y_train_reshaped=y_train.values.reshape(-1,1)
x_test_reshaped=x_test.values.reshape(-1,1)
y_test_reshaped=y_test.values.reshape(-1,1)

In [13]:
from sklearn.linear_model import LinearRegression

In [17]:
lin_reg=LinearRegression().fit(x_train_reshaped,y_train_reshaped)


LinearRegression()


In [20]:
y_pred=lin_reg.predict(x_test_reshaped)
print(y_pred)

[[115814.30756236]
 [ 71511.92534771]
 [102617.85328566]
 [ 75282.34085534]
 [ 55487.65944028]
 [ 60200.67882482]
 [122412.53470072]
 [107330.8726702 ]
 [ 63028.49045554]
 [ 35692.97802523]]


In [18]:
print(lin_reg.coef_)

[[9426.03876907]]


In [19]:
print(lin_reg.intercept_)

[25324.33537924]


In [22]:
y_train_pred=lin_reg.predict(x_train_reshaped)
print(y_train_pred)

[[ 46061.62067121]
 [ 73397.13310153]
 [ 52659.84780956]
 [ 63971.09433245]
 [ 63028.49045554]
 [ 99790.04165494]
 [ 37578.18577904]
 [ 39463.39353286]
 [110158.68430092]
 [ 44176.41291739]
 [ 92249.21063968]
 [114871.70368546]
 [ 80937.96411679]
 [124297.74245453]
 [ 89421.39900895]
 [ 55487.65944028]
 [ 62085.88657864]
 [ 67741.50984008]
 [ 81880.56799369]
 [ 53602.45168647]]


In [23]:
y_test_pred=lin_reg.predict(x_test_reshaped)
print(y_test_pred)

[[115814.30756236]
 [ 71511.92534771]
 [102617.85328566]
 [ 75282.34085534]
 [ 55487.65944028]
 [ 60200.67882482]
 [122412.53470072]
 [107330.8726702 ]
 [ 63028.49045554]
 [ 35692.97802523]]


In [24]:
from sklearn.metrics import r2_score ,mean_squared_error,mean_absolute_error
print(r2_score(y_train_reshaped,y_train_pred))

0.9549236946181227


In [26]:
print(mean_squared_error(y_train_reshaped,y_train_pred))

29793161.082422983


In [27]:
print(mean_absolute_error(y_train_reshaped,y_train_pred))

4472.274104679318
